# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 323857529a07efd1f8d210e5426aab56fab237f1484a9ecfc618025c85a68b5793bdcc72945c3596b214d652eab9099593565b0f95f9d627cc43e60b1c33e766

test:
  secret_key_base: 16fc22c6f9b60917bd817f792b22f5fc92ca8f673c3c065e0a3871b0d02ea9685706df732064bcd9a98930bc6061aff1a26294ace2fe2df1abfb882ce0203029

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
